//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ResponsabilidadPrincipal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_ResponsabilidadPrincipal()
        {
            this.Cat_IndicadorDesempeno = new HashSet<Cat_IndicadorDesempeno>();
        }
    
        public int ResponsabilidadId { get; set; }
        public int DependenciaEjeId { get; set; }
        public string DescripcionResponsabilidad { get; set; }
        public byte Habilitado { get; set; }
    
        public virtual Cat_DependenciaEje Cat_DependenciaEje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_IndicadorDesempeno> Cat_IndicadorDesempeno { get; set; }
    }
}
