//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Acciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Acciones()
        {
            this.Cat_SubAcciones = new HashSet<Cat_SubAcciones>();
            this.tb_Agenda = new HashSet<tb_Agenda>();
        }
    
        public int AccionesID { get; set; }
        public string AccionesNombre { get; set; }
        public Nullable<int> subprogramaId { get; set; }
        public Nullable<int> IdPrograma { get; set; }
    
        public virtual TB_subprograma TB_subprograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_SubAcciones> Cat_SubAcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Agenda> tb_Agenda { get; set; }
    }
}
