//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonias
    {
        public int id { get; set; }
        public string colonia { get; set; }
        public int MunicipioID { get; set; }
        public bool prioritario { get; set; }
    
        public virtual Municipios Municipios { get; set; }
    }
}
