//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public int LocalidadID { get; set; }
        public Nullable<int> MunicipioID { get; set; }
        public string CLAVE { get; set; }
        public string Localidad { get; set; }
    
        public virtual Municipios Municipios { get; set; }
    }
}
