//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Municipios()
        {
            this.Localidades = new HashSet<Localidades>();
            this.Colonias = new HashSet<Colonias>();
        }
    
        public int MunicipioID { get; set; }
        public string CLAVE { get; set; }
        public string MUNICIPIO { get; set; }
        public Nullable<int> DelegacionID { get; set; }
        public Nullable<int> ZonaID { get; set; }
        public Nullable<int> idzona { get; set; }
        public Nullable<bool> prioritario { get; set; }
        public Nullable<bool> p_indigena { get; set; }
        public Nullable<bool> programa_istmo { get; set; }
    
        public virtual Cat_Delegacion Cat_Delegacion { get; set; }
        public virtual cat_Zona_Estado cat_Zona_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localidades> Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colonias> Colonias { get; set; }
    }
}
