//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personales()
        {
            this.tc_PoliciaenTucolonia = new HashSet<tc_PoliciaenTucolonia>();
            this.tb_Reporte_Diario = new HashSet<tb_Reporte_Diario>();
        }
    
        public int Personalid { get; set; }
        public Nullable<int> cat_areaidarea { get; set; }
        public string Nombre { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string AreaTrabajo { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<System.DateTime> fechacrecion { get; set; }
        public string login { get; set; }
        public Nullable<System.Guid> guidUsuario { get; set; }
        public string passwd { get; set; }
        public Nullable<System.Guid> RolesId { get; set; }
        public string RolesNombre { get; set; }
        public string Dependencia { get; set; }
        public Nullable<int> DependenciaId { get; set; }
    
        public virtual Cat_area Cat_area { get; set; }
        public virtual Cat_Dependencias Cat_Dependencias { get; set; }
        public virtual Cat_Region Cat_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_PoliciaenTucolonia> tc_PoliciaenTucolonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Reporte_Diario> tb_Reporte_Diario { get; set; }
    }
}
