//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIICOPEntities : DbContext
    {
        public SIICOPEntities()
            : base("name=SIICOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Acciones> Cat_Acciones { get; set; }
        public virtual DbSet<Cat_area> Cat_area { get; set; }
        public virtual DbSet<Cat_Delegacion> Cat_Delegacion { get; set; }
        public virtual DbSet<Cat_Dependencias> Cat_Dependencias { get; set; }
        public virtual DbSet<Cat_Region> Cat_Region { get; set; }
        public virtual DbSet<Cat_SubAcciones> Cat_SubAcciones { get; set; }
        public virtual DbSet<cat_Zona_Estado> cat_Zona_Estado { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Personales> Personales { get; set; }
        public virtual DbSet<PersonalUsuario> PersonalUsuario { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<tb_AcionesBeneficiadosXmes> tb_AcionesBeneficiadosXmes { get; set; }
        public virtual DbSet<tb_Agenda> tb_Agenda { get; set; }
        public virtual DbSet<tb_Beneficiados_dgprs> tb_Beneficiados_dgprs { get; set; }
        public virtual DbSet<tb_DireccionReporte> tb_DireccionReporte { get; set; }
        public virtual DbSet<tb_fotografia> tb_fotografia { get; set; }
        public virtual DbSet<tb_programa> tb_programa { get; set; }
        public virtual DbSet<TB_subprograma> TB_subprograma { get; set; }
        public virtual DbSet<tbAuditoria> tbAuditoria { get; set; }
        public virtual DbSet<tbCarga_trabajo_Dele> tbCarga_trabajo_Dele { get; set; }
        public virtual DbSet<tc_PoliciaenTucolonia> tc_PoliciaenTucolonia { get; set; }
        public virtual DbSet<tc_Seguimiento> tc_Seguimiento { get; set; }
        public virtual DbSet<tcCuadrantes> tcCuadrantes { get; set; }
        public virtual DbSet<tcMunicipiosPoliColonia> tcMunicipiosPoliColonia { get; set; }
        public virtual DbSet<tcPeticionCiudadana> tcPeticionCiudadana { get; set; }
        public virtual DbSet<tcPoliciaColonias> tcPoliciaColonias { get; set; }
        public virtual DbSet<tcProblematicaMunicipal> tcProblematicaMunicipal { get; set; }
        public virtual DbSet<tcProblematicaSeguridad> tcProblematicaSeguridad { get; set; }
        public virtual DbSet<tcProblematicaVialidad> tcProblematicaVialidad { get; set; }
        public virtual DbSet<vw_Indicadores_Acciones> vw_Indicadores_Acciones { get; set; }
        public virtual DbSet<vw_Indicadores_Acciones_Convenios> vw_Indicadores_Acciones_Convenios { get; set; }
        public virtual DbSet<vw_Indicadores_Beneficiados> vw_Indicadores_Beneficiados { get; set; }
        public virtual DbSet<Wv_DatosReportesHistorico> Wv_DatosReportesHistorico { get; set; }
        public virtual DbSet<WV_Datosrepote_app> WV_Datosrepote_app { get; set; }
        public virtual DbSet<wv_personaluser> wv_personaluser { get; set; }
        public virtual DbSet<wv_PeticionesForPoliciaIntegralProxi> wv_PeticionesForPoliciaIntegralProxi { get; set; }
        public virtual DbSet<wv_progra_sub_acciones> wv_progra_sub_acciones { get; set; }
        public virtual DbSet<wv_reportesGeneralExcel> wv_reportesGeneralExcel { get; set; }
        public virtual DbSet<Wv_TotalAcciones> Wv_TotalAcciones { get; set; }
        public virtual DbSet<Wv_TotalSubprogramas> Wv_TotalSubprogramas { get; set; }
        public virtual DbSet<tc_zona> tc_zona { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Colonias> Colonias { get; set; }
        public virtual DbSet<tc_coordinacion> tc_coordinacion { get; set; }
        public virtual DbSet<Cat_Eje> Cat_Eje { get; set; }
        public virtual DbSet<Cat_Entorno> Cat_Entorno { get; set; }
        public virtual DbSet<TB_DatosGralReporte> TB_DatosGralReporte { get; set; }
        public virtual DbSet<tb_Reporte_Diario> tb_Reporte_Diario { get; set; }
    
        public virtual int CrearReporteEscolar(string descractividad, string atendioactividadper, Nullable<int> accionesID, Nullable<System.DateTime> fecha, Nullable<int> personalid, Nullable<int> programasID, Nullable<int> subprogramaId, Nullable<int> totalHombresAtendidos, Nullable<int> totalMujeresAtendidas, Nullable<int> total_atendidos, string capturaapp, string delegacion, string nombrelugarescul, string nombreContacto, string telcel, string clavePlantel, string nivel, string turno, string niñas, string niños, string hombres, string mujeres, string docentesH, string docentesM, string direccionGoogle, string latitud, string longitud, string estado, string calle, string coloni, Nullable<int> localidadID, Nullable<int> municipioID, Nullable<int> regionID, Nullable<int> delegacionID, string entrecalle1, string entrecalle2)
        {
            var descractividadParameter = descractividad != null ?
                new ObjectParameter("descractividad", descractividad) :
                new ObjectParameter("descractividad", typeof(string));
    
            var atendioactividadperParameter = atendioactividadper != null ?
                new ObjectParameter("atendioactividadper", atendioactividadper) :
                new ObjectParameter("atendioactividadper", typeof(string));
    
            var accionesIDParameter = accionesID.HasValue ?
                new ObjectParameter("AccionesID", accionesID) :
                new ObjectParameter("AccionesID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var personalidParameter = personalid.HasValue ?
                new ObjectParameter("Personalid", personalid) :
                new ObjectParameter("Personalid", typeof(int));
    
            var programasIDParameter = programasID.HasValue ?
                new ObjectParameter("programasID", programasID) :
                new ObjectParameter("programasID", typeof(int));
    
            var subprogramaIdParameter = subprogramaId.HasValue ?
                new ObjectParameter("subprogramaId", subprogramaId) :
                new ObjectParameter("subprogramaId", typeof(int));
    
            var totalHombresAtendidosParameter = totalHombresAtendidos.HasValue ?
                new ObjectParameter("TotalHombresAtendidos", totalHombresAtendidos) :
                new ObjectParameter("TotalHombresAtendidos", typeof(int));
    
            var totalMujeresAtendidasParameter = totalMujeresAtendidas.HasValue ?
                new ObjectParameter("TotalMujeresAtendidas", totalMujeresAtendidas) :
                new ObjectParameter("TotalMujeresAtendidas", typeof(int));
    
            var total_atendidosParameter = total_atendidos.HasValue ?
                new ObjectParameter("total_atendidos", total_atendidos) :
                new ObjectParameter("total_atendidos", typeof(int));
    
            var capturaappParameter = capturaapp != null ?
                new ObjectParameter("capturaapp", capturaapp) :
                new ObjectParameter("capturaapp", typeof(string));
    
            var delegacionParameter = delegacion != null ?
                new ObjectParameter("Delegacion", delegacion) :
                new ObjectParameter("Delegacion", typeof(string));
    
            var nombrelugaresculParameter = nombrelugarescul != null ?
                new ObjectParameter("nombrelugarescul", nombrelugarescul) :
                new ObjectParameter("nombrelugarescul", typeof(string));
    
            var nombreContactoParameter = nombreContacto != null ?
                new ObjectParameter("NombreContacto", nombreContacto) :
                new ObjectParameter("NombreContacto", typeof(string));
    
            var telcelParameter = telcel != null ?
                new ObjectParameter("telcel", telcel) :
                new ObjectParameter("telcel", typeof(string));
    
            var clavePlantelParameter = clavePlantel != null ?
                new ObjectParameter("ClavePlantel", clavePlantel) :
                new ObjectParameter("ClavePlantel", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("Turno", turno) :
                new ObjectParameter("Turno", typeof(string));
    
            var niñasParameter = niñas != null ?
                new ObjectParameter("niñas", niñas) :
                new ObjectParameter("niñas", typeof(string));
    
            var niñosParameter = niños != null ?
                new ObjectParameter("niños", niños) :
                new ObjectParameter("niños", typeof(string));
    
            var hombresParameter = hombres != null ?
                new ObjectParameter("hombres", hombres) :
                new ObjectParameter("hombres", typeof(string));
    
            var mujeresParameter = mujeres != null ?
                new ObjectParameter("mujeres", mujeres) :
                new ObjectParameter("mujeres", typeof(string));
    
            var docentesHParameter = docentesH != null ?
                new ObjectParameter("docentesH", docentesH) :
                new ObjectParameter("docentesH", typeof(string));
    
            var docentesMParameter = docentesM != null ?
                new ObjectParameter("docentesM", docentesM) :
                new ObjectParameter("docentesM", typeof(string));
    
            var direccionGoogleParameter = direccionGoogle != null ?
                new ObjectParameter("DireccionGoogle", direccionGoogle) :
                new ObjectParameter("DireccionGoogle", typeof(string));
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("Latitud", latitud) :
                new ObjectParameter("Latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("Longitud", longitud) :
                new ObjectParameter("Longitud", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var coloniParameter = coloni != null ?
                new ObjectParameter("coloni", coloni) :
                new ObjectParameter("coloni", typeof(string));
    
            var localidadIDParameter = localidadID.HasValue ?
                new ObjectParameter("LocalidadID", localidadID) :
                new ObjectParameter("LocalidadID", typeof(int));
    
            var municipioIDParameter = municipioID.HasValue ?
                new ObjectParameter("MunicipioID", municipioID) :
                new ObjectParameter("MunicipioID", typeof(int));
    
            var regionIDParameter = regionID.HasValue ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(int));
    
            var delegacionIDParameter = delegacionID.HasValue ?
                new ObjectParameter("DelegacionID", delegacionID) :
                new ObjectParameter("DelegacionID", typeof(int));
    
            var entrecalle1Parameter = entrecalle1 != null ?
                new ObjectParameter("Entrecalle1", entrecalle1) :
                new ObjectParameter("Entrecalle1", typeof(string));
    
            var entrecalle2Parameter = entrecalle2 != null ?
                new ObjectParameter("Entrecalle2", entrecalle2) :
                new ObjectParameter("Entrecalle2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearReporteEscolar", descractividadParameter, atendioactividadperParameter, accionesIDParameter, fechaParameter, personalidParameter, programasIDParameter, subprogramaIdParameter, totalHombresAtendidosParameter, totalMujeresAtendidasParameter, total_atendidosParameter, capturaappParameter, delegacionParameter, nombrelugaresculParameter, nombreContactoParameter, telcelParameter, clavePlantelParameter, nivelParameter, turnoParameter, niñasParameter, niñosParameter, hombresParameter, mujeresParameter, docentesHParameter, docentesMParameter, direccionGoogleParameter, latitudParameter, longitudParameter, estadoParameter, calleParameter, coloniParameter, localidadIDParameter, municipioIDParameter, regionIDParameter, delegacionIDParameter, entrecalle1Parameter, entrecalle2Parameter);
        }
    
        public virtual int CrearReporteGeneral(string descractividad, string atendioactividadper, Nullable<int> accionesID, Nullable<System.DateTime> fecha, Nullable<int> personalid, Nullable<int> programasID, Nullable<int> subprogramaId, Nullable<int> totalHombresAtendidos, Nullable<int> totalMujeresAtendidas, Nullable<int> total_atendidos, string capturaapp, string delegacion, string nombrelugarescul, string nombreContacto, string telcel, string direccionGoogle, string latitud, string longitud, string estado, string calle, string coloni, Nullable<int> localidadID, Nullable<int> municipioID, Nullable<int> regionID, Nullable<int> delegacionID, string entrecalle1, string entrecalle2)
        {
            var descractividadParameter = descractividad != null ?
                new ObjectParameter("descractividad", descractividad) :
                new ObjectParameter("descractividad", typeof(string));
    
            var atendioactividadperParameter = atendioactividadper != null ?
                new ObjectParameter("atendioactividadper", atendioactividadper) :
                new ObjectParameter("atendioactividadper", typeof(string));
    
            var accionesIDParameter = accionesID.HasValue ?
                new ObjectParameter("AccionesID", accionesID) :
                new ObjectParameter("AccionesID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var personalidParameter = personalid.HasValue ?
                new ObjectParameter("Personalid", personalid) :
                new ObjectParameter("Personalid", typeof(int));
    
            var programasIDParameter = programasID.HasValue ?
                new ObjectParameter("programasID", programasID) :
                new ObjectParameter("programasID", typeof(int));
    
            var subprogramaIdParameter = subprogramaId.HasValue ?
                new ObjectParameter("subprogramaId", subprogramaId) :
                new ObjectParameter("subprogramaId", typeof(int));
    
            var totalHombresAtendidosParameter = totalHombresAtendidos.HasValue ?
                new ObjectParameter("TotalHombresAtendidos", totalHombresAtendidos) :
                new ObjectParameter("TotalHombresAtendidos", typeof(int));
    
            var totalMujeresAtendidasParameter = totalMujeresAtendidas.HasValue ?
                new ObjectParameter("TotalMujeresAtendidas", totalMujeresAtendidas) :
                new ObjectParameter("TotalMujeresAtendidas", typeof(int));
    
            var total_atendidosParameter = total_atendidos.HasValue ?
                new ObjectParameter("total_atendidos", total_atendidos) :
                new ObjectParameter("total_atendidos", typeof(int));
    
            var capturaappParameter = capturaapp != null ?
                new ObjectParameter("capturaapp", capturaapp) :
                new ObjectParameter("capturaapp", typeof(string));
    
            var delegacionParameter = delegacion != null ?
                new ObjectParameter("Delegacion", delegacion) :
                new ObjectParameter("Delegacion", typeof(string));
    
            var nombrelugaresculParameter = nombrelugarescul != null ?
                new ObjectParameter("nombrelugarescul", nombrelugarescul) :
                new ObjectParameter("nombrelugarescul", typeof(string));
    
            var nombreContactoParameter = nombreContacto != null ?
                new ObjectParameter("NombreContacto", nombreContacto) :
                new ObjectParameter("NombreContacto", typeof(string));
    
            var telcelParameter = telcel != null ?
                new ObjectParameter("telcel", telcel) :
                new ObjectParameter("telcel", typeof(string));
    
            var direccionGoogleParameter = direccionGoogle != null ?
                new ObjectParameter("DireccionGoogle", direccionGoogle) :
                new ObjectParameter("DireccionGoogle", typeof(string));
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("Latitud", latitud) :
                new ObjectParameter("Latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("Longitud", longitud) :
                new ObjectParameter("Longitud", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var coloniParameter = coloni != null ?
                new ObjectParameter("coloni", coloni) :
                new ObjectParameter("coloni", typeof(string));
    
            var localidadIDParameter = localidadID.HasValue ?
                new ObjectParameter("LocalidadID", localidadID) :
                new ObjectParameter("LocalidadID", typeof(int));
    
            var municipioIDParameter = municipioID.HasValue ?
                new ObjectParameter("MunicipioID", municipioID) :
                new ObjectParameter("MunicipioID", typeof(int));
    
            var regionIDParameter = regionID.HasValue ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(int));
    
            var delegacionIDParameter = delegacionID.HasValue ?
                new ObjectParameter("DelegacionID", delegacionID) :
                new ObjectParameter("DelegacionID", typeof(int));
    
            var entrecalle1Parameter = entrecalle1 != null ?
                new ObjectParameter("Entrecalle1", entrecalle1) :
                new ObjectParameter("Entrecalle1", typeof(string));
    
            var entrecalle2Parameter = entrecalle2 != null ?
                new ObjectParameter("Entrecalle2", entrecalle2) :
                new ObjectParameter("Entrecalle2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearReporteGeneral", descractividadParameter, atendioactividadperParameter, accionesIDParameter, fechaParameter, personalidParameter, programasIDParameter, subprogramaIdParameter, totalHombresAtendidosParameter, totalMujeresAtendidasParameter, total_atendidosParameter, capturaappParameter, delegacionParameter, nombrelugaresculParameter, nombreContactoParameter, telcelParameter, direccionGoogleParameter, latitudParameter, longitudParameter, estadoParameter, calleParameter, coloniParameter, localidadIDParameter, municipioIDParameter, regionIDParameter, delegacionIDParameter, entrecalle1Parameter, entrecalle2Parameter);
        }
    
        public virtual int CrearReporteRedVer(string descractividad, string atendioactividadper, Nullable<int> accionesID, Nullable<System.DateTime> fecha, Nullable<int> personalid, Nullable<int> programasID, Nullable<int> subprogramaId, Nullable<int> totalHombresAtendidos, Nullable<int> totalMujeresAtendidas, Nullable<int> total_atendidos, string capturaapp, string delegacion, string nombrelugarescul, string nombreContacto, string telcel, string clavePlantel, string nivel, string turno, string niñas, string niños, string hombres, string mujeres, string docentesH, string docentesM, string empreH, string empreM, string actoresH, string actoresM, string ciudaH, string ciudaM, string muniH, string muniM, Nullable<int> ambito, string direccionGoogle, string latitud, string longitud, string estado, string calle, string coloni, Nullable<int> localidadID, Nullable<int> municipioID, Nullable<int> regionID, Nullable<int> delegacionID, string entrecalle1, string entrecalle2)
        {
            var descractividadParameter = descractividad != null ?
                new ObjectParameter("descractividad", descractividad) :
                new ObjectParameter("descractividad", typeof(string));
    
            var atendioactividadperParameter = atendioactividadper != null ?
                new ObjectParameter("atendioactividadper", atendioactividadper) :
                new ObjectParameter("atendioactividadper", typeof(string));
    
            var accionesIDParameter = accionesID.HasValue ?
                new ObjectParameter("AccionesID", accionesID) :
                new ObjectParameter("AccionesID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var personalidParameter = personalid.HasValue ?
                new ObjectParameter("Personalid", personalid) :
                new ObjectParameter("Personalid", typeof(int));
    
            var programasIDParameter = programasID.HasValue ?
                new ObjectParameter("programasID", programasID) :
                new ObjectParameter("programasID", typeof(int));
    
            var subprogramaIdParameter = subprogramaId.HasValue ?
                new ObjectParameter("subprogramaId", subprogramaId) :
                new ObjectParameter("subprogramaId", typeof(int));
    
            var totalHombresAtendidosParameter = totalHombresAtendidos.HasValue ?
                new ObjectParameter("TotalHombresAtendidos", totalHombresAtendidos) :
                new ObjectParameter("TotalHombresAtendidos", typeof(int));
    
            var totalMujeresAtendidasParameter = totalMujeresAtendidas.HasValue ?
                new ObjectParameter("TotalMujeresAtendidas", totalMujeresAtendidas) :
                new ObjectParameter("TotalMujeresAtendidas", typeof(int));
    
            var total_atendidosParameter = total_atendidos.HasValue ?
                new ObjectParameter("total_atendidos", total_atendidos) :
                new ObjectParameter("total_atendidos", typeof(int));
    
            var capturaappParameter = capturaapp != null ?
                new ObjectParameter("capturaapp", capturaapp) :
                new ObjectParameter("capturaapp", typeof(string));
    
            var delegacionParameter = delegacion != null ?
                new ObjectParameter("Delegacion", delegacion) :
                new ObjectParameter("Delegacion", typeof(string));
    
            var nombrelugaresculParameter = nombrelugarescul != null ?
                new ObjectParameter("nombrelugarescul", nombrelugarescul) :
                new ObjectParameter("nombrelugarescul", typeof(string));
    
            var nombreContactoParameter = nombreContacto != null ?
                new ObjectParameter("NombreContacto", nombreContacto) :
                new ObjectParameter("NombreContacto", typeof(string));
    
            var telcelParameter = telcel != null ?
                new ObjectParameter("telcel", telcel) :
                new ObjectParameter("telcel", typeof(string));
    
            var clavePlantelParameter = clavePlantel != null ?
                new ObjectParameter("ClavePlantel", clavePlantel) :
                new ObjectParameter("ClavePlantel", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("Nivel", nivel) :
                new ObjectParameter("Nivel", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("Turno", turno) :
                new ObjectParameter("Turno", typeof(string));
    
            var niñasParameter = niñas != null ?
                new ObjectParameter("niñas", niñas) :
                new ObjectParameter("niñas", typeof(string));
    
            var niñosParameter = niños != null ?
                new ObjectParameter("niños", niños) :
                new ObjectParameter("niños", typeof(string));
    
            var hombresParameter = hombres != null ?
                new ObjectParameter("hombres", hombres) :
                new ObjectParameter("hombres", typeof(string));
    
            var mujeresParameter = mujeres != null ?
                new ObjectParameter("mujeres", mujeres) :
                new ObjectParameter("mujeres", typeof(string));
    
            var docentesHParameter = docentesH != null ?
                new ObjectParameter("docentesH", docentesH) :
                new ObjectParameter("docentesH", typeof(string));
    
            var docentesMParameter = docentesM != null ?
                new ObjectParameter("docentesM", docentesM) :
                new ObjectParameter("docentesM", typeof(string));
    
            var empreHParameter = empreH != null ?
                new ObjectParameter("empreH", empreH) :
                new ObjectParameter("empreH", typeof(string));
    
            var empreMParameter = empreM != null ?
                new ObjectParameter("empreM", empreM) :
                new ObjectParameter("empreM", typeof(string));
    
            var actoresHParameter = actoresH != null ?
                new ObjectParameter("actoresH", actoresH) :
                new ObjectParameter("actoresH", typeof(string));
    
            var actoresMParameter = actoresM != null ?
                new ObjectParameter("actoresM", actoresM) :
                new ObjectParameter("actoresM", typeof(string));
    
            var ciudaHParameter = ciudaH != null ?
                new ObjectParameter("ciudaH", ciudaH) :
                new ObjectParameter("ciudaH", typeof(string));
    
            var ciudaMParameter = ciudaM != null ?
                new ObjectParameter("ciudaM", ciudaM) :
                new ObjectParameter("ciudaM", typeof(string));
    
            var muniHParameter = muniH != null ?
                new ObjectParameter("muniH", muniH) :
                new ObjectParameter("muniH", typeof(string));
    
            var muniMParameter = muniM != null ?
                new ObjectParameter("muniM", muniM) :
                new ObjectParameter("muniM", typeof(string));
    
            var ambitoParameter = ambito.HasValue ?
                new ObjectParameter("ambito", ambito) :
                new ObjectParameter("ambito", typeof(int));
    
            var direccionGoogleParameter = direccionGoogle != null ?
                new ObjectParameter("DireccionGoogle", direccionGoogle) :
                new ObjectParameter("DireccionGoogle", typeof(string));
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("Latitud", latitud) :
                new ObjectParameter("Latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("Longitud", longitud) :
                new ObjectParameter("Longitud", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var calleParameter = calle != null ?
                new ObjectParameter("calle", calle) :
                new ObjectParameter("calle", typeof(string));
    
            var coloniParameter = coloni != null ?
                new ObjectParameter("coloni", coloni) :
                new ObjectParameter("coloni", typeof(string));
    
            var localidadIDParameter = localidadID.HasValue ?
                new ObjectParameter("LocalidadID", localidadID) :
                new ObjectParameter("LocalidadID", typeof(int));
    
            var municipioIDParameter = municipioID.HasValue ?
                new ObjectParameter("MunicipioID", municipioID) :
                new ObjectParameter("MunicipioID", typeof(int));
    
            var regionIDParameter = regionID.HasValue ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(int));
    
            var delegacionIDParameter = delegacionID.HasValue ?
                new ObjectParameter("DelegacionID", delegacionID) :
                new ObjectParameter("DelegacionID", typeof(int));
    
            var entrecalle1Parameter = entrecalle1 != null ?
                new ObjectParameter("Entrecalle1", entrecalle1) :
                new ObjectParameter("Entrecalle1", typeof(string));
    
            var entrecalle2Parameter = entrecalle2 != null ?
                new ObjectParameter("Entrecalle2", entrecalle2) :
                new ObjectParameter("Entrecalle2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearReporteRedVer", descractividadParameter, atendioactividadperParameter, accionesIDParameter, fechaParameter, personalidParameter, programasIDParameter, subprogramaIdParameter, totalHombresAtendidosParameter, totalMujeresAtendidasParameter, total_atendidosParameter, capturaappParameter, delegacionParameter, nombrelugaresculParameter, nombreContactoParameter, telcelParameter, clavePlantelParameter, nivelParameter, turnoParameter, niñasParameter, niñosParameter, hombresParameter, mujeresParameter, docentesHParameter, docentesMParameter, empreHParameter, empreMParameter, actoresHParameter, actoresMParameter, ciudaHParameter, ciudaMParameter, muniHParameter, muniMParameter, ambitoParameter, direccionGoogleParameter, latitudParameter, longitudParameter, estadoParameter, calleParameter, coloniParameter, localidadIDParameter, municipioIDParameter, regionIDParameter, delegacionIDParameter, entrecalle1Parameter, entrecalle2Parameter);
        }
    
        public virtual int GetActividades(Nullable<int> personaID)
        {
            var personaIDParameter = personaID.HasValue ?
                new ObjectParameter("personaID", personaID) :
                new ObjectParameter("personaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetActividades", personaIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_Elimninar_Actividades(Nullable<System.Guid> idResumen, string userName, string area)
        {
            var idResumenParameter = idResumen.HasValue ?
                new ObjectParameter("IdResumen", idResumen) :
                new ObjectParameter("IdResumen", typeof(System.Guid));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimninar_Actividades", idResumenParameter, userNameParameter, areaParameter);
        }
    
        public virtual int sp_folio_actividad(Nullable<System.Guid> actividadID, string inicialProgra, string extencion)
        {
            var actividadIDParameter = actividadID.HasValue ?
                new ObjectParameter("ActividadID", actividadID) :
                new ObjectParameter("ActividadID", typeof(System.Guid));
    
            var inicialPrograParameter = inicialProgra != null ?
                new ObjectParameter("InicialProgra", inicialProgra) :
                new ObjectParameter("InicialProgra", typeof(string));
    
            var extencionParameter = extencion != null ?
                new ObjectParameter("extencion", extencion) :
                new ObjectParameter("extencion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_folio_actividad", actividadIDParameter, inicialPrograParameter, extencionParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_limpia_log()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_limpia_log");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Reporte_Acciones_Beneficiados(Nullable<int> tipo, Nullable<int> mes, Nullable<int> ano, Nullable<int> programa)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var programaParameter = programa.HasValue ?
                new ObjectParameter("programa", programa) :
                new ObjectParameter("programa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Reporte_Acciones_Beneficiados", tipoParameter, mesParameter, anoParameter, programaParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<GetConsulActividades_Result> GetConsulActividades(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, string dependencia, Nullable<int> zona, Nullable<int> programa, Nullable<int> municipio, Nullable<int> localidad, string institucionesP)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var dependenciaParameter = dependencia != null ?
                new ObjectParameter("Dependencia", dependencia) :
                new ObjectParameter("Dependencia", typeof(string));
    
            var zonaParameter = zona.HasValue ?
                new ObjectParameter("Zona", zona) :
                new ObjectParameter("Zona", typeof(int));
    
            var programaParameter = programa.HasValue ?
                new ObjectParameter("Programa", programa) :
                new ObjectParameter("Programa", typeof(int));
    
            var municipioParameter = municipio.HasValue ?
                new ObjectParameter("Municipio", municipio) :
                new ObjectParameter("Municipio", typeof(int));
    
            var localidadParameter = localidad.HasValue ?
                new ObjectParameter("Localidad", localidad) :
                new ObjectParameter("Localidad", typeof(int));
    
            var institucionesPParameter = institucionesP != null ?
                new ObjectParameter("InstitucionesP", institucionesP) :
                new ObjectParameter("InstitucionesP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConsulActividades_Result>("GetConsulActividades", fechaInicialParameter, fechaFinalParameter, dependenciaParameter, zonaParameter, programaParameter, municipioParameter, localidadParameter, institucionesPParameter);
        }
    }
}
