//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Agenda
    {
        public int AgendaId { get; set; }
        public Nullable<System.DateTime> fechaevento { get; set; }
        public Nullable<int> Idprograma { get; set; }
        public Nullable<int> IDSubprograma { get; set; }
        public Nullable<int> AccionesId { get; set; }
        public string HoraActividad { get; set; }
        public string SalidaActividad { get; set; }
        public string LugarEvento { get; set; }
        public string DireccionEvento { get; set; }
        public string Contacto { get; set; }
        public string Participantes { get; set; }
        public string Traslado { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Cat_Acciones Cat_Acciones { get; set; }
        public virtual tb_programa tb_programa { get; set; }
        public virtual TB_subprograma TB_subprograma { get; set; }
    }
}
