//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AcionesBeneficiadosXmes
    {
        public int idAccionesBeni { get; set; }
        public Nullable<int> programa { get; set; }
        public string mesTEX { get; set; }
        public string MesInt { get; set; }
        public Nullable<int> cifra { get; set; }
        public Nullable<int> TipoB_A { get; set; }
        public Nullable<int> Tipo_t_p { get; set; }
        public Nullable<int> Año { get; set; }
    }
}
