//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Beneficiados_dgprs
    {
        public int BeneficiadosDGPRS_ID { get; set; }
        public Nullable<System.Guid> idResumenDiario { get; set; }
        public Nullable<int> AlumH_0_4 { get; set; }
        public Nullable<int> AlummM_0_4 { get; set; }
        public Nullable<int> AlumH_5_8 { get; set; }
        public Nullable<int> AlumM_5_8 { get; set; }
        public Nullable<int> AlumH_9_12 { get; set; }
        public Nullable<int> AlumM_9_12 { get; set; }
        public Nullable<int> AlumH_13_15 { get; set; }
        public Nullable<int> AlumM_13_15 { get; set; }
        public Nullable<int> AlumH_16_18 { get; set; }
        public Nullable<int> AlumM_16_18 { get; set; }
        public Nullable<int> AlumH_19_22 { get; set; }
        public Nullable<int> AlumM_19_22 { get; set; }
        public Nullable<int> AlumH_23_60 { get; set; }
        public Nullable<int> AlumM_23_60 { get; set; }
        public Nullable<int> AlumH_61_mas { get; set; }
        public Nullable<int> AlumM_61_mas { get; set; }
        public Nullable<int> Padre_Docent_H_0_4 { get; set; }
        public Nullable<int> Padre_Docent_M_0_4 { get; set; }
        public Nullable<int> Padre_Docent_H_5_8 { get; set; }
        public Nullable<int> Padre_Docent_M_5_8 { get; set; }
        public Nullable<int> Padre_Docent_H_9_12 { get; set; }
        public Nullable<int> Padre_Docent_M_9_12 { get; set; }
        public Nullable<int> Padre_Docent_H_13_15 { get; set; }
        public Nullable<int> Padre_Docent_M_13_15 { get; set; }
        public Nullable<int> Padre_Docent_H_16_18 { get; set; }
        public Nullable<int> Padre_Docent_M_16_18 { get; set; }
        public Nullable<int> Padre_Docent_H_19_22 { get; set; }
        public Nullable<int> Padre_Docent_M_19_22 { get; set; }
        public Nullable<int> Padre_Docent_H_23_60 { get; set; }
        public Nullable<int> Padre_Docent_M_23_60 { get; set; }
        public Nullable<int> Padre_Docent_H_61_mas { get; set; }
        public Nullable<int> Padre_Docent_M_61_mas { get; set; }
        public Nullable<int> Per_Publi_Priva_H_0_4 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_0_4 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_5_8 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_5_8 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_9_12 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_9_12 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_13_15 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_13_15 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_16_18 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_16_18 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_19_22 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_19_22 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_23_60 { get; set; }
        public Nullable<int> Per_Publi_Priva_M_23_60 { get; set; }
        public Nullable<int> Per_Publi_Priva_H_61_mas { get; set; }
        public Nullable<int> Per_Publi_Priva_M_61_mas { get; set; }
        public Nullable<int> Interno_H_0_4 { get; set; }
        public Nullable<int> Interno_M_0_4 { get; set; }
        public Nullable<int> Interno_H_5_8 { get; set; }
        public Nullable<int> Interno_M_5_8 { get; set; }
        public Nullable<int> Interno_H_9_12 { get; set; }
        public Nullable<int> Interno_M_9_12 { get; set; }
        public Nullable<int> Interno_H_13_15 { get; set; }
        public Nullable<int> Interno_M_13_15 { get; set; }
        public Nullable<int> Interno_H_16_18 { get; set; }
        public Nullable<int> Interno_M_16_18 { get; set; }
        public Nullable<int> Interno_H_19_22 { get; set; }
        public Nullable<int> Interno_M_19_22 { get; set; }
        public Nullable<int> Interno_H_23_60 { get; set; }
        public Nullable<int> Interno_M_23_60 { get; set; }
        public Nullable<int> Interno_H_61_mas { get; set; }
        public Nullable<int> Interno_M_61_mas { get; set; }
        public Nullable<int> Familiar_H_0_4 { get; set; }
        public Nullable<int> Familiar_M_0_4 { get; set; }
        public Nullable<int> Familiar_H_5_8 { get; set; }
        public Nullable<int> Familiar_M_5_8 { get; set; }
        public Nullable<int> Familiar_H_9_12 { get; set; }
        public Nullable<int> Familiar_M_9_12 { get; set; }
        public Nullable<int> Familiar_H_13_15 { get; set; }
        public Nullable<int> Familiar_M_13_15 { get; set; }
        public Nullable<int> Familiar_H_16_18 { get; set; }
        public Nullable<int> Familiar_M_16_18 { get; set; }
        public Nullable<int> Familiar_H_19_22 { get; set; }
        public Nullable<int> Familiar_M_19_22 { get; set; }
        public Nullable<int> Familiar_H_23_60 { get; set; }
        public Nullable<int> Familiar_M_23_60 { get; set; }
        public Nullable<int> Familiar_H_61_mas { get; set; }
        public Nullable<int> Familiar_M_61_mas { get; set; }
        public Nullable<int> HijosInter_H_0_4 { get; set; }
        public Nullable<int> HijosInter_M_0_4 { get; set; }
        public Nullable<int> HijosInter_H_5_8 { get; set; }
        public Nullable<int> HijosInter_M_5_8 { get; set; }
        public Nullable<int> HijosInter_H_9_12 { get; set; }
        public Nullable<int> HijosInter_M_9_12 { get; set; }
        public Nullable<int> HijosInter_H_13_15 { get; set; }
        public Nullable<int> HijosInter_M_13_15 { get; set; }
        public Nullable<int> HijosInter_H_16_18 { get; set; }
        public Nullable<int> HijosInter_M_16_18 { get; set; }
        public Nullable<int> HijosInter_H_19_22 { get; set; }
        public Nullable<int> HijosInter_M_19_22 { get; set; }
        public Nullable<int> HijosInter_H_23_60 { get; set; }
        public Nullable<int> HijosInter_M_23_60 { get; set; }
        public Nullable<int> HijosInter_H_61_mas { get; set; }
        public Nullable<int> HijosInter_M_61_mas { get; set; }
        public Nullable<int> Prelibera_H_0_4 { get; set; }
        public Nullable<int> Prelibera_M_0_4 { get; set; }
        public Nullable<int> Prelibera_H_5_8 { get; set; }
        public Nullable<int> Prelibera_M_5_8 { get; set; }
        public Nullable<int> Prelibera_H_9_12 { get; set; }
        public Nullable<int> Prelibera_M_9_12 { get; set; }
        public Nullable<int> Prelibera_H_13_15 { get; set; }
        public Nullable<int> Prelibera_M_13_15 { get; set; }
        public Nullable<int> Prelibera_H_16_18 { get; set; }
        public Nullable<int> Prelibera_M_16_18 { get; set; }
        public Nullable<int> Prelibera_H_19_22 { get; set; }
        public Nullable<int> Prelibera_M_19_22 { get; set; }
        public Nullable<int> Prelibera_H_23_60 { get; set; }
        public Nullable<int> Prelibera_M_23_60 { get; set; }
        public Nullable<int> Prelibera_H_61_mas { get; set; }
        public Nullable<int> Prelibera_M_61_mas { get; set; }
        public Nullable<int> Total_H_0_4 { get; set; }
        public Nullable<int> Total_M_0_4 { get; set; }
        public Nullable<int> Total_0_4 { get; set; }
        public Nullable<int> Total_H_5_8 { get; set; }
        public Nullable<int> Total_M_5_8 { get; set; }
        public Nullable<int> Total_5_8 { get; set; }
        public Nullable<int> Total_H_9_12 { get; set; }
        public Nullable<int> Total_M_9_12 { get; set; }
        public Nullable<int> Total_9_12 { get; set; }
        public Nullable<int> Total_H_13_15 { get; set; }
        public Nullable<int> Total_M_13_15 { get; set; }
        public Nullable<int> Total_13_15 { get; set; }
        public Nullable<int> Total_H_16_18 { get; set; }
        public Nullable<int> Total_M_16_18 { get; set; }
        public Nullable<int> Total_16_18 { get; set; }
        public Nullable<int> Total_H_19_22 { get; set; }
        public Nullable<int> Total_M_19_22 { get; set; }
        public Nullable<int> Total_19_22 { get; set; }
        public Nullable<int> Total_H_23_60 { get; set; }
        public Nullable<int> Total_M_23_60 { get; set; }
        public Nullable<int> Total_23_60 { get; set; }
        public Nullable<int> Total_H_61_mas { get; set; }
        public Nullable<int> Total_M_61_mas { get; set; }
        public Nullable<int> Total_61_mas { get; set; }
    
        public virtual tb_Reporte_Diario tb_Reporte_Diario { get; set; }
    }
}
