//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DatosGralReporte
    {
        public int DatosGralReporteID { get; set; }
        public string NombreLugar_Escuela { get; set; }
        public string NombreContacto { get; set; }
        public string telcel { get; set; }
        public string ClavePlantel { get; set; }
        public string Nivel { get; set; }
        public string Turno { get; set; }
        public Nullable<int> niñas { get; set; }
        public Nullable<int> niños { get; set; }
        public Nullable<int> hombres { get; set; }
        public Nullable<int> mujeres { get; set; }
        public Nullable<int> docentesH { get; set; }
        public Nullable<int> docentesM { get; set; }
        public Nullable<System.Guid> idResumenDiario { get; set; }
        public Nullable<int> EmpreH { get; set; }
        public Nullable<int> EmpreM { get; set; }
        public Nullable<int> AgremiadoM { get; set; }
        public Nullable<int> AgremiadoH { get; set; }
        public Nullable<int> CiudadanoH { get; set; }
        public Nullable<int> CiudadanoM { get; set; }
        public Nullable<int> PrecidentemuniH { get; set; }
        public Nullable<int> PrecidentemuniM { get; set; }
        public Nullable<int> ActoresSocialM { get; set; }
        public Nullable<int> ActoresSocialH { get; set; }
        public string Requerimeintos { get; set; }
        public Nullable<bool> MuniSItuaVulnera { get; set; }
        public Nullable<bool> MuniAlerGene { get; set; }
        public Nullable<bool> PoblaIndi { get; set; }
        public Nullable<bool> Munidelic { get; set; }
        public Nullable<int> Ambito { get; set; }
        public Nullable<int> EjeId { get; set; }
        public Nullable<int> otrosH { get; set; }
        public Nullable<int> otrosm { get; set; }
        public Nullable<bool> plantel_diagnosticado { get; set; }
        public string inst_participantes { get; set; }
        public string tema_impartido { get; set; }
        public Nullable<bool> casos_ravi { get; set; }
        public Nullable<int> nocasos_ravi { get; set; }
        public string dirigido { get; set; }
        public string giro_comercios { get; set; }
        public Nullable<int> no_acciones_dgpvi { get; set; }
        public Nullable<int> no_acciones_institucionales { get; set; }
        public Nullable<int> total_acciones_ravi { get; set; }
        public Nullable<bool> ofrecieron_segurichat { get; set; }
        public string segurichat { get; set; }
        public Nullable<int> ResponsabilidadId { get; set; }
        public Nullable<int> IndicadorId { get; set; }
    
        public virtual Cat_IndicadorDesempeno Cat_IndicadorDesempeno { get; set; }
        public virtual Cat_ResponsabilidadPrincipal Cat_ResponsabilidadPrincipal { get; set; }
        public virtual tb_Reporte_Diario tb_Reporte_Diario { get; set; }
    }
}
