//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DireccionReporte
    {
        public int Idubicacion { get; set; }
        public string DireccionGoogle { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string estado { get; set; }
        public string calle { get; set; }
        public string coloni { get; set; }
        public Nullable<int> LocalidadID { get; set; }
        public Nullable<int> MunicipioID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> DelegacionID { get; set; }
        public Nullable<System.Guid> idResumenDiario { get; set; }
        public string Entrecalle1 { get; set; }
        public string Entrecalle2 { get; set; }
        public Nullable<int> Cuadrante { get; set; }
        public Nullable<bool> mpio_prioritario { get; set; }
        public Nullable<bool> mpio_homicidio { get; set; }
        public Nullable<bool> col_prioritario { get; set; }
        public Nullable<bool> mpio_indigena { get; set; }
        public Nullable<bool> programa_istmo { get; set; }
    
        public virtual tb_Reporte_Diario tb_Reporte_Diario { get; set; }
    }
}
