//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fotografia
    {
        public int idfotgrafia { get; set; }
        public string ImagenExtencion { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> ImagenSubida { get; set; }
        public Nullable<int> fileSize { get; set; }
        public string contentType { get; set; }
        public string FileName { get; set; }
        public string piefoto { get; set; }
        public Nullable<System.Guid> idResumenDiario { get; set; }
        public string ImgBase64 { get; set; }
    
        public virtual tb_Reporte_Diario tb_Reporte_Diario { get; set; }
    }
}
