//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_programa()
        {
            this.tb_Agenda = new HashSet<tb_Agenda>();
            this.TB_subprograma = new HashSet<TB_subprograma>();
            this.tb_Reporte_Diario = new HashSet<tb_Reporte_Diario>();
        }
    
        public int programasID { get; set; }
        public string NombrePrograma { get; set; }
        public Nullable<int> DependenciaId { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Cat_Dependencias Cat_Dependencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Agenda> tb_Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_subprograma> TB_subprograma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Reporte_Diario> tb_Reporte_Diario { get; set; }
    }
}
