//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Reporte_Diario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Reporte_Diario()
        {
            this.tb_Beneficiados_dgprs = new HashSet<tb_Beneficiados_dgprs>();
            this.TB_DatosGralReporte = new HashSet<TB_DatosGralReporte>();
            this.tb_DireccionReporte = new HashSet<tb_DireccionReporte>();
            this.tb_fotografia = new HashSet<tb_fotografia>();
        }
    
        public System.Guid idResumenDiario { get; set; }
        public string descripcion_actividad { get; set; }
        public string personal_atendio_actividad { get; set; }
        public string seguimiento { get; set; }
        public Nullable<int> AccionesID { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string coordinador { get; set; }
        public Nullable<int> idzona { get; set; }
        public Nullable<int> idcoordinacion { get; set; }
        public Nullable<int> Personalid { get; set; }
        public Nullable<int> programasID { get; set; }
        public Nullable<int> subprogramaId { get; set; }
        public string accion_implementada { get; set; }
        public Nullable<int> TotalHombresAtendidos { get; set; }
        public Nullable<int> TotalMujeresAtendidas { get; set; }
        public Nullable<int> total_atendidos { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> fechacaptura { get; set; }
        public string capturaAPP { get; set; }
        public string DelegacionOcoonurbacion { get; set; }
        public string FolioActividad { get; set; }
        public int idReportreFOL { get; set; }
    
        public virtual Personales Personales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Beneficiados_dgprs> tb_Beneficiados_dgprs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DatosGralReporte> TB_DatosGralReporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DireccionReporte> tb_DireccionReporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fotografia> tb_fotografia { get; set; }
        public virtual tb_programa tb_programa { get; set; }
        public virtual TB_subprograma TB_subprograma { get; set; }
    }
}
