//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_subprograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_subprograma()
        {
            this.Cat_Acciones = new HashSet<Cat_Acciones>();
            this.tb_Agenda = new HashSet<tb_Agenda>();
            this.tb_Reporte_Diario = new HashSet<tb_Reporte_Diario>();
        }
    
        public int subprogramaId { get; set; }
        public string NombreSubPrograma { get; set; }
        public Nullable<int> programasID { get; set; }
        public Nullable<int> ProgramaCompartidoID { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Acciones> Cat_Acciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Agenda> tb_Agenda { get; set; }
        public virtual tb_programa tb_programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Reporte_Diario> tb_Reporte_Diario { get; set; }
    }
}
