//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAuditoria
    {
        public int AuditoriaId { get; set; }
        public Nullable<System.Guid> auditoriaGuid { get; set; }
        public string usuario { get; set; }
        public string area { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idTipomodificacion { get; set; }
        public string PagModificacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string IdABC { get; set; }
    }
}
