//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarga_trabajo_Dele
    {
        public int CargaTrabjaoId { get; set; }
        public Nullable<int> programa { get; set; }
        public string Mes_letra { get; set; }
        public Nullable<int> Mes_Num { get; set; }
        public Nullable<int> Tipo_TA_BA_TB { get; set; }
        public Nullable<int> cifra { get; set; }
        public string Delegacion { get; set; }
        public Nullable<int> Año { get; set; }
    }
}
