//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_coordinacion
    {
        public int idcoordinacion { get; set; }
        public string coordinacion { get; set; }
        public int idzona { get; set; }
    
        public virtual tc_zona tc_zona { get; set; }
    }
}
