//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_PoliciaenTucolonia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tc_PoliciaenTucolonia()
        {
            this.tc_Seguimiento = new HashSet<tc_Seguimiento>();
            this.tcProblematicaVialidad = new HashSet<tcProblematicaVialidad>();
        }
    
        public System.Guid IdCaptura { get; set; }
        public int idcapturaInt { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaCpturaEvento { get; set; }
    
        public virtual Personales Personales { get; set; }
        public virtual tcMunicipiosPoliColonia tcMunicipiosPoliColonia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_Seguimiento> tc_Seguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcProblematicaVialidad> tcProblematicaVialidad { get; set; }
    }
}
