//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_Seguimiento
    {
        public System.Guid IdSeguimiento { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> Colonia { get; set; }
        public string calle { get; set; }
        public string Referencia { get; set; }
        public Nullable<bool> sexo { get; set; }
        public Nullable<int> IdCuadrante { get; set; }
        public string Correo { get; set; }
        public Nullable<int> idcapturaInt { get; set; }
        public Nullable<System.Guid> IdCaptura { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaRepor { get; set; }
    
        public virtual tc_PoliciaenTucolonia tc_PoliciaenTucolonia { get; set; }
        public virtual tcPoliciaColonias tcPoliciaColonias { get; set; }
    }
}
