//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcPeticionCiudadana
    {
        public int Id { get; set; }
        public Nullable<int> seguridadcolonia { get; set; }
        public Nullable<int> casa { get; set; }
        public Nullable<int> escuela { get; set; }
        public Nullable<int> mercado { get; set; }
        public Nullable<int> centrocomercial { get; set; }
        public Nullable<int> TransportePublico { get; set; }
        public Nullable<int> Parques { get; set; }
        public Nullable<int> trabajo { get; set; }
        public Nullable<int> calle { get; set; }
        public Nullable<int> banco { get; set; }
        public Nullable<int> automovil { get; set; }
        public Nullable<int> cajeroauto { get; set; }
        public Nullable<int> carretera { get; set; }
        public Nullable<int> transporte { get; set; }
        public Nullable<System.Guid> IdCaptura { get; set; }
        public Nullable<bool> protebentrevecinos { get; set; }
        public Nullable<bool> victima_delito { get; set; }
        public string ano { get; set; }
        public string cualfuedelito { get; set; }
        public Nullable<bool> conocelosprogramasdgvi { get; set; }
        public Nullable<bool> escuelasegura { get; set; }
        public Nullable<bool> fomentodeportivo { get; set; }
        public Nullable<bool> redesvecinales { get; set; }
        public Nullable<bool> prevencionvm { get; set; }
        public Nullable<bool> empresasegura { get; set; }
        public Nullable<bool> limpiezaespaciospubli { get; set; }
        public string cualesonfehcahoralugar { get; set; }
        public string observacionpropuesta { get; set; }
        public string oficial1 { get; set; }
        public string distintivo1 { get; set; }
        public string oficial2 { get; set; }
        public string distintivo2 { get; set; }
        public Nullable<int> idcapturaInt { get; set; }
    }
}
