//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcPoliciaColonias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcPoliciaColonias()
        {
            this.tc_Seguimiento = new HashSet<tc_Seguimiento>();
        }
    
        public int ColoniasId { get; set; }
        public string NombreColonia { get; set; }
        public Nullable<int> IdCuadrante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_Seguimiento> tc_Seguimiento { get; set; }
        public virtual tcCuadrantes tcCuadrantes { get; set; }
    }
}
