//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcProblematicaSeguridad
    {
        public int Id { get; set; }
        public Nullable<bool> Aplica { get; set; }
        public Nullable<bool> NoAplica { get; set; }
        public Nullable<bool> Robos { get; set; }
        public Nullable<bool> Homicidios { get; set; }
        public Nullable<bool> ConsumoAlcohol { get; set; }
        public Nullable<bool> Pandillerismo { get; set; }
        public Nullable<bool> Grafitis { get; set; }
        public Nullable<bool> Narcomenudeo { get; set; }
        public Nullable<bool> Cristalazos { get; set; }
        public Nullable<bool> ConflictosVecinales { get; set; }
        public Nullable<bool> conflictosescuelas { get; set; }
        public string ubicacionseguridad { get; set; }
        public string Especifique { get; set; }
        public Nullable<System.Guid> IdCaptura { get; set; }
        public Nullable<int> idcapturaInt { get; set; }
    }
}
