//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcProblematicaMunicipal
    {
        public int Id { get; set; }
        public Nullable<bool> LimpiaPublicaDeficiente { get; set; }
        public Nullable<bool> FaltaAlumbradoPublico { get; set; }
        public Nullable<bool> ParquesJardinesEnDeterioro { get; set; }
        public Nullable<bool> DrenajeExpuesto { get; set; }
        public Nullable<bool> AnimalesCallejero { get; set; }
        public Nullable<bool> Ambulantaje { get; set; }
        public Nullable<bool> FugaAguaPotable { get; set; }
        public Nullable<bool> ColaderasTapadas { get; set; }
        public Nullable<bool> MonteMaleza { get; set; }
        public Nullable<bool> baches { get; set; }
        public Nullable<bool> acerasdeterioradas { get; set; }
        public Nullable<bool> Aplica { get; set; }
        public Nullable<bool> NoAplica { get; set; }
        public string Especifique { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> idcapturaInt { get; set; }
        public Nullable<System.Guid> IdCaptura { get; set; }
    }
}
