//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcProblematicaVialidad
    {
        public int Id { get; set; }
        public Nullable<bool> Aplica { get; set; }
        public Nullable<bool> NoAplica { get; set; }
        public Nullable<bool> AutosMacetas { get; set; }
        public Nullable<bool> FaltaReductoresVelocidad { get; set; }
        public Nullable<bool> AutosDobleCarril { get; set; }
        public Nullable<bool> congestionvehicular { get; set; }
        public Nullable<bool> FaltaSeñalizaciones { get; set; }
        public Nullable<bool> otros { get; set; }
        public string Ubicacion { get; set; }
        public string Especifique { get; set; }
        public Nullable<System.Guid> IdCaptura { get; set; }
        public Nullable<int> idcapturaInt { get; set; }
    
        public virtual tc_PoliciaenTucolonia tc_PoliciaenTucolonia { get; set; }
    }
}
