//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Indicadores_Beneficiados
    {
        public int programasID { get; set; }
        public Nullable<int> SumaTotal { get; set; }
        public Nullable<int> Suma_Obtenidos_B { get; set; }
        public Nullable<int> ENERO { get; set; }
        public Nullable<int> ENERO_OBTENIDO_B { get; set; }
        public Nullable<int> FEBRERO { get; set; }
        public Nullable<int> FEBRERO_OBTENIDO_B { get; set; }
        public Nullable<int> MARZO { get; set; }
        public Nullable<int> MARZO_OBTENIDO_B { get; set; }
        public Nullable<int> ABRIL { get; set; }
        public Nullable<int> ABRIL_OBTENIDO_B { get; set; }
        public Nullable<int> MAYO { get; set; }
        public Nullable<int> MAYO_OBTENIDO_B { get; set; }
        public Nullable<int> JUNIO { get; set; }
        public Nullable<int> JUNIO_OBTENIDO_B { get; set; }
        public Nullable<int> JULIO { get; set; }
        public Nullable<int> JULIO_OBTENIDO_B { get; set; }
        public Nullable<int> AGOSTO { get; set; }
        public Nullable<int> AGOSTO_OBTENIDO_B { get; set; }
        public Nullable<int> SEPTIEMBRE { get; set; }
        public Nullable<int> SEPTIEMBRE_OBTENIDO_B { get; set; }
        public Nullable<int> OCTUBRE { get; set; }
        public Nullable<int> OCTUBRE_OBTENIDO_B { get; set; }
        public Nullable<int> NOVIEMBRE { get; set; }
        public Nullable<int> NOVIEMBRE_OBTENIDO_B { get; set; }
        public Nullable<int> DICIEMBRE { get; set; }
        public Nullable<int> DICIEMBRE_OBTENIDO_B { get; set; }
    }
}
