//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Indicadores_Acciones_Convenios
    {
        public int programasID { get; set; }
        public string NombrePrograma { get; set; }
        public Nullable<int> ENERO { get; set; }
        public Nullable<int> FEBRERO { get; set; }
        public Nullable<int> MARZO { get; set; }
        public Nullable<int> ABRIL { get; set; }
        public Nullable<int> MAYO { get; set; }
        public Nullable<int> JUNIO { get; set; }
        public Nullable<int> JULIO { get; set; }
        public Nullable<int> AGOSTO { get; set; }
        public Nullable<int> SEPTIEMBRE { get; set; }
        public Nullable<int> OCTUBRE { get; set; }
        public Nullable<int> NOVIEMBRE { get; set; }
        public Nullable<int> DICIEMBRE { get; set; }
    }
}
