//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WV_Datosrepote_app
    {
        public string fecha { get; set; }
        public Nullable<int> Personalid { get; set; }
        public string Expr1 { get; set; }
        public Nullable<int> cat_areaidarea { get; set; }
        public string AreaTrabajo { get; set; }
        public string NombrePrograma { get; set; }
        public Nullable<int> programasID { get; set; }
        public Nullable<int> subprogramaId { get; set; }
        public string NombreSubPrograma { get; set; }
        public Nullable<int> AccionesID { get; set; }
        public string AccionesNombre { get; set; }
        public Nullable<int> TotalHombresAtendidos { get; set; }
        public Nullable<int> TotalMujeresAtendidas { get; set; }
        public Nullable<int> total_atendidos { get; set; }
        public System.Guid idResumenDiario { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
        public string descripcion_actividad { get; set; }
        public string personal_atendio_actividad { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> DelegacionID { get; set; }
        public Nullable<System.DateTime> fechacaptura { get; set; }
    }
}
