//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_personaluser
    {
        public int Personalid { get; set; }
        public string nombre { get; set; }
        public string AreaTrabajo { get; set; }
        public string RolesNombre { get; set; }
        public Nullable<int> cat_areaidarea { get; set; }
        public string Dependencia { get; set; }
        public string Delegacíon { get; set; }
        public string login { get; set; }
        public string Password { get; set; }
        public string RoleName { get; set; }
    }
}
