//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_progra_sub_acciones
    {
        public int programasID { get; set; }
        public string NombrePrograma { get; set; }
        public int subprogramaId { get; set; }
        public string NombreSubPrograma { get; set; }
        public string AccionesNombre { get; set; }
        public Nullable<int> AccionesID { get; set; }
    }
}
