//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_PeticionesForPoliciaIntegralProxi
    {
        public System.Guid IdCaptura { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<System.DateTime> fechaRepor { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string Correo { get; set; }
        public string telefono { get; set; }
        public string MunicipioNombre { get; set; }
        public Nullable<int> CuadranteNombre { get; set; }
        public string NombreColonia { get; set; }
        public string AplicaSeguridad { get; set; }
        public string Robos { get; set; }
        public string Homicidios { get; set; }
        public string ConsumoAlcohol { get; set; }
        public string Pandillerismo { get; set; }
        public string Grafitis { get; set; }
        public string Narcomenudeo { get; set; }
        public string Cristalazos { get; set; }
        public string ConflictosVecinales { get; set; }
        public string conflictosescuelas { get; set; }
        public string ubicacionseguridad { get; set; }
        public string Especifique { get; set; }
        public string AplicaVilidad { get; set; }
        public string AutosMacetas { get; set; }
        public string FaltaReductoresVelocidad { get; set; }
        public string AutosDobleCarril { get; set; }
        public string congestionvehicular { get; set; }
        public string FaltaSeñalizaciones { get; set; }
        public string otros { get; set; }
        public string Ubicacion { get; set; }
        public string EspecifiqueViali { get; set; }
        public string AplicaMunicipal { get; set; }
        public string LimpiaPublicaDeficiente { get; set; }
        public string FaltaAlumbradoPublico { get; set; }
        public string ParquesJardinesEnDeterioro { get; set; }
        public string DrenajeExpuesto { get; set; }
        public string AnimalesCallejero { get; set; }
        public string Ambulantaje { get; set; }
        public string FugaAguaPotable { get; set; }
        public string ColaderasTapadas { get; set; }
        public string MonteMaleza { get; set; }
        public string baches { get; set; }
        public string acerasdeterioradas { get; set; }
        public string EspecifiqueMuni { get; set; }
        public string UbicacionMuni { get; set; }
        public Nullable<int> seguridadcolonia { get; set; }
        public Nullable<int> casa { get; set; }
        public Nullable<int> escuela { get; set; }
        public Nullable<int> mercado { get; set; }
        public Nullable<int> centrocomercial { get; set; }
        public Nullable<int> TransportePublico { get; set; }
        public Nullable<int> Parques { get; set; }
        public Nullable<int> trabajo { get; set; }
        public Nullable<int> calle { get; set; }
        public Nullable<int> banco { get; set; }
        public Nullable<int> automovil { get; set; }
        public Nullable<int> cajeroauto { get; set; }
        public Nullable<int> carretera { get; set; }
        public Nullable<int> transporte { get; set; }
        public string protebentrevecinos { get; set; }
        public string victima_delito { get; set; }
        public string ano { get; set; }
        public string cualfuedelito { get; set; }
        public string conocelosprogramasdgvi { get; set; }
        public string escuelasegura { get; set; }
        public string fomentodeportivo { get; set; }
        public string redesvecinales { get; set; }
        public string prevencionvm { get; set; }
        public string empresasegura { get; set; }
        public string limpiezaespaciospubli { get; set; }
        public string cualesonfehcahoralugar { get; set; }
        public string observacionpropuesta { get; set; }
        public string oficial1 { get; set; }
        public string distintivo1 { get; set; }
        public string oficial2 { get; set; }
        public string distintivo2 { get; set; }
    }
}
