//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIICOP_V1._2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wv_TotalSubprogramas
    {
        public string NombrePrograma { get; set; }
        public Nullable<int> programasID { get; set; }
        public string NombreSubPrograma { get; set; }
        public int SubProgramas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
